### PR TITLE
updates for egs5 program and stdhep tools and lhe readers

### PR DESCRIPTION
**Pull request by tongtongcao**
ESG5 programs are updated by Takashi:

lhe_rad.f: program for RAD smaple
lhe_prompt.f: program for ap prompt sample
llhe_exponential.f: program for ap displaced sample with "exponential-decay" model
lhe_uniform.f: program for ap displaced sample with "uniform-decay" model
stdhep_tools: add_mother_update2.cc
Parent particles for final-state particles from EGS5 output are added into events so that fully truth information can be included in the final data sample. To do so, information from both MadGraph and EGS5 outputs are used.

lhe readers are developed by Stanislava, which are used to parse lhe files into root files:
lhetree_Ap.cc for ap sample
lhetree_Rad.cc for rad sample
lhetree_SIMP.cc for SIMP sample
lhetree_TriTrig.cc for tritrig sample
lhetree_WAB.cc for wab sample

Makefile in stdhep-tools is modified since ROOT libraries are used for new codes.

### CODE REVIEW

**Comment by tongtongcao** [comment]
> wrapper

**Comment by JeremyMcCormick** [comment]
> ESG5 programs are updated by Takashi:

This should be an entirely separate PR.

> lhe readers are developed by Stanislava, which are used to parse lhe files into root files:

Should also be a separate PR.

"lhetree_Ap.cc for ap sample
lhetree_Rad.cc for rad sample
..."

Can't we do something more reasonable here like have a generic lhetree program which has a flag for Ap, Rad, etc. 

> Makefile in stdhep-tools is modified since ROOT libraries are used for new codes.

This is not going to be acceptable right now as it is will require a ROOT environment to be setup before building hps-mc, which is not something I want to add. It should also not be something that is put into the stdhep-tools Makefile until we review and possibly restructure it. The ROOT config would need to be pushed up into the top-level CMake file so that it is handled consistently, should we decide to actually add a ROOT dependency.

**Comment by JeremyMcCormick** [comment]
"stdhep_tools: add_mother_update2.cc"

How about calling this add_mother_with_final_states instead since "update2" is not clear at all?

**Comment by JeremyMcCormick** [comment]
> The new eg5 fortran scripts should also be added to StdHepConverter in the python wrapper so they can be called just as the existing tools are.

I can do this once we get to that point, though I think we need to first figure out how to organize and structure all these new tools before it is even relevant.

**Comment by JeremyMcCormick** [comment]
I'm closing this after discussion with @tongtongcao and @cbravo135.

**Pull request closed without merging**
