### PR TITLE
Tritrig beam dev

### PR DESCRIPTION
**Pull request by cbravo135**
New type of job to produce tritrig+beam reco starting with running slic on bunched beam and trigtrig stdhep files that have already been "rotated".

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
I think this is probably dependent on #238 being merged first or there's likely to be conflicts. There will probably be conflicts either way, but it looks like merging the larger PR first will result in fewer conflicts since this PR only has a few changes to the relevant files, which should be easier to cleanup.

**Comment by cbravo135** [comment]
No such conflicts exist. I just merged from master automatically with the git recursive merger.

**Comment by cbravo135** [comment]
It was not "likely to be some major conflicts introduced". This change was orthogonal.

**Comment by JeremyMcCormick** [comment]
I assume you fully verified the changes to tools.py and the other python code? Which examples were checked?

**Review by JeremyMcCormick — APPROVED** [review]
Discussed changes to .py files and seems fine

**Pull request merged**
